### ISSUE TITLE
Missing trainer_Unflow_DP in Core

### ISSUE THREAD

**Issue by lala-sean** [FrancisXZhang/DAEVI#1]
Dear authors @FrancisXZhang , thanks for releasing the code of your great work. 
May I check if the `core` lib is all-inclusive? I cannot find `trainer_Unflow_DP`. Will you release the training part by any chance? Thank you so much

**Comment by FrancisXZhang** [comment]
Hi,

Thank you for reaching out and bringing this to our attention! We’re happy to share all the training details. Regarding the trainer_Unflow_DP script, I will check and upload any missing files.

Cheers,
Francis

**Comment by lala-sean** [comment]
> Hi,
> 
> Thank you for reaching out and bringing this to our attention! We’re happy to share all the training details. Regarding the trainer_Unflow_DP script, I will check and upload any missing files.
> 
> Cheers, Francis

Thank you so much for your prompt response! Also, the depth_layer and depth_model seem missed. Many thanks!

**Comment by FrancisXZhang** [comment]
Hi,

I've updated those files in the current repository. Although I attached the related code, please note that the depth-related models are pre-trained based on others' work. You can access their pre-trained models from their code repository here: [AF-SfMLearner](https://github.com/ShuweiShao/AF-SfMLearner).

If you are interested in directly using the depth ground truth we inferred with AF-SfMLearner, I'm happy to share it as well. However, it's quite large (hundreds of GBs), so I will need some time to find an efficient way to upload and share it.

Cheers, 
Francis

**Comment by lala-sean** [comment]
> Hi,
> 
> I've updated those files in the current repository. Although I attached the related code, please note that the depth-related models are pre-trained based on others' work. You can access their pre-trained models from their code repository here: [AF-SfMLearner](https://github.com/ShuweiShao/AF-SfMLearner).
> 
> If you are interested in directly using the depth ground truth we inferred with AF-SfMLearner, I'm happy to share it as well. However, it's quite large (hundreds of GBs), so I will need some time to find an efficient way to upload and share it.
> 
> Cheers, Francis

Hi, thank you so much for updating the code. Appreciate it!

**Comment by FrancisXZhang** [comment]
Great, I'm closing this issue now, but please don't hesitate to reach out if you encounter any further issues or have questions about implementing our work.
